name: Benchmark

on:
  push:
    branches: [ main ]

jobs:

  benchmark-amd64:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - run: brew install lima docker
    - run: limactl start ./lima/docker-amd64.yaml
  
    - name: Set DOCKER_HOST
      run: echo "::set-output name=value::$(limactl list docker-amd64 --format 'unix://{{.Dir}}/sock/docker.sock')"
      id: set-docker-host

    - run: echo $DOCKER_HOST
      env:
        DOCKER_HOST: ${{ steps.set-docker-host.outputs.value }}
    - name: Run docker build
      run: docker build -t nextjs .
      env:
        DOCKER_HOST: ${{ steps.set-docker-host.outputs.value }}