name: Benchmark

on:
  push:
    branches: [ main ]

jobs:

  benchmark-amd64:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Lima
      run: ./.github/actions/setup-lima
      with:
        lima-config-file: ./lima/docker-amd64.yaml
      id: lima

    - name: Run docker build
      run: docker build -t nextjs .
      env:
        DOCKER_HOST: ${{ steps.lima.outputs.docker-host }}
