name: Benchmark

on:
  push:
    branches: [ main ]

jobs:

  benchmark-amd64:

    runs-on: macos-11
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Lima
      id: lima
      uses: ./.github/actions/setup-lima
      with:
        lima-config-file: ./lima/docker-amd64.yaml

    - name: Run docker build
      run: docker build -t nextjs .
      env:
        DOCKER_HOST: ${{ steps.lima.outputs.docker-host }}

  benchmark-arm64:

    runs-on: macos-11
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Lima
      id: lima
      uses: ./.github/actions/setup-lima
      with:
        lima-config-file: ./lima/docker-arm64.yaml

    - run: |
        ls ~/.lima/*/ha.*.log
        cat ~/.lima/*/ha.*.log
      if: ${{ always() }}

    - name: Run docker build
      run: docker build -t nextjs .
      env:
        DOCKER_HOST: ${{ steps.lima.outputs.docker-host }}


  benchmark-fast-mode:

    runs-on: macos-11
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Lima
      id: lima
      uses: ./.github/actions/setup-lima

    - name: Setup nerdctl
      run: |
        lima sudo systemctl start containerd
        lima sudo nerdctl run --privileged --rm tonistiigi/binfmt --install all

    - name: Run docker build (AMD64)
      run: lima nerdctl build --platform=amd64 -t nextjs .

    - name: Run docker build (ARM64)
      run: lima nerdctl build --platform=arm64 -t nextjs .
